# Dockerfile for image: matlabruntime/r2025b/release/update0/108000000000000000
# 
# Sample docker build command:
# docker build -f "Dockerfile.runtime" -t matlabruntime/r2025b/release/update0/108000000000000000 "."

FROM containers.mathworks.com/matlab-runtime-utils/matlab-runtime-installer:r2025b AS installer
LABEL "mathworks.matlab.runtime.cleanup"="true"

ENV EXTRACTEDDIR="/opt/matlabruntime/unzippedinstaller"

WORKDIR $EXTRACTEDDIR

# Write the installer file
RUN touch ./installInputs.txt
RUN printf "destinationFolder=/tmp/matlabruntime/runtime\nagreeToLicense=yes\n" > ./installInputs.txt
RUN printf "product.MATLAB Base Runtime\n" >> ./installInputs.txt
RUN printf "product.MATLAB Production Server Runtime Addon\n" >> ./installInputs.txt

# Run the installer
RUN ./install -bat true -inputFile ./installInputs.txt

FROM matlabruntimebase/r2025b/release/update0
LABEL "mathworks.matlab.runtime.cleanup"="false"

ENV TZ="Etc/UTC"

COPY --from=installer /tmp/matlabruntime/runtime /opt/matlabruntime

RUN unlink /opt/matlabruntime/R2025b/sys/os/glnxa64/libstdc++.so.6
RUN ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/matlabruntime/R2025b/sys/os/glnxa64/libstdc++.so.6

ENV LD_LIBRARY_PATH="/opt/matlabruntime/R2025b/runtime/glnxa64:/opt/matlabruntime/R2025b/bin/glnxa64:/opt/matlabruntime/R2025b/sys/os/glnxa64:/opt/matlabruntime/R2025b/sys/opengl/lib/glnxa64:/opt/matlabruntime/R2025b/extern/bin/glnxa64"

